### ISSUE TITLE
Android node does not find node_modules if script is in different directory

### ISSUE THREAD

**Issue by deefactorial** [jxcore/jxcore-cordova#28]
The Error I get is this:

```
05-19 16:02:23.420  23267-23267/com.openmoney.p2p E/jxcore-log﹕ Error:
05-19 16:02:23.424  23267-23267/com.openmoney.p2p E/jxcore-log﹕ Cannot find module 'superagent'
05-19 16:02:23.424  23267-23267/com.openmoney.p2p E/jxcore-log﹕ (module.js 696:14)
05-19 16:02:23.424  23267-23267/com.openmoney.p2p E/jxcore-log﹕ at Module._oldRes (module.js:696:15)
            at Module._resolveFilename (module.js:1385:1)
            at Module._load (module.js:268:18)
            at Module.prototype.require (module.js:378:10)
            at require (module.js:396:12)
            at /data/data/com.openmoney.p2p/files/www/jxcore/test/basic.js:10:13
            at Module.prototype._compile (module.js:519:10)
            at Module._extensions[".js"] (module.js:549:1)
            at Module.prototype.load (module.js:3
```

in my app.js 

I run 
`requre("./test/basic.js")`

in the `basic.js` javascript file I have a `require("superaget")`

I suspect it's looking for the node_modules in the test directory even though they are located in the jxcore directory.

you can find [my repo here](https://github.com/deefactorial/jxcore-cordova-tests.git) folow the instructions in the README.md to setup. To test this works on the desktop goto `www/jxcore` folder and run `node test.js` to test on android run `cordova run android`.

**Comment by deefactorial** [comment]
I reran the test and it works.
